### ISSUE TITLE
'GHG emissions, primary metal production' includes all primary production, not only metals

### ISSUE THREAD

**Issue by nheeren** [YaleCIE/RECC-ODYM#10]
The result export for "GHG emissions, primary metal production" is equal to the sum of all processes that begin with "GHG emissions, production of primary...". So, I suggest to either rename the result category or include only metals.

Also, "GHG emissions, primary metal production" is being exported twice.

**Comment by stefanpauliuk** [comment]
Need better future GHG inventory of Primary material production, Niko/Edgar: zwei Szenarien: NCP und RCP 2.6. ALL, extract energy consumption and different GHG as separate. Mid May.
        + https://www.agora-energiewende.de/veroeffentlichungen/klimaneutrale-industrie/

**Comment by stefanpauliuk** [comment]
The Agora report does contain useful information, and I will now add an RCP scenario dimension to both the primary production energy consumption parameter (4_EI_ProcessEnergyIntensity_V2.2) and the prim.prod GHG parameter (4_PE_ProcessExtensions_V3.4, all supply chain GHG other than those related to energy carriers covered by 4_EI_ProcessEnergyIntensity_V2.2) to capture the available scenarios.

That means we can include scenarios such as hydrogen-based primary steel production in the RCP 2.6 scenario, which I think is realistic and at least one major steel makers has a concrete plan for such a switch already.
The next challenge is then to find a good scenario for GHG of future hydrogen production. Here the MESSAGE data are not helpful (too many gaps) but in the worst case, we can translate hydrogen into electricity demand using current electrolyser efficiencies.
One piece after the other is falling into place...

We also need a decent documentations of the current GHG factors created by Laurent.

**Comment by stefanpauliuk** [comment]
We now have RCP2.6-compatible descriptions of future steel making based on hydrogen, plus a simple description of hydrogen supply linked to average future electricity supply. 
The inventories for Cu and Al will be kept for the moment but can be split during revision into their process and el-based part, the latter than can also be linked to the electricity supply system.

**Comment by Hertwich** [comment]
Hi Stefan, I was under the impression that we already were using electricity in these process descriptions.

**Comment by stefanpauliuk** [comment]
We do now for some of the processes (steelmaking with hydrogen), where I took hydrogen-related emissions out of the emissions factor and moved them over to 4_EI_ProcessEnergyIntensity_V2.2 instead, from where they are linked to the energy supply GHG factors in the model.
We have now a reasonable set of emissions factors, and further revision is possible (e.g., for Al and Cu) but not a high priority in my opinion, plus that I don't see that we have capacity to tackle this issue now.
For Al and Cu: Keep previous calculations, can update later by splitting into process and el-based emissions
