### ISSUE TITLE
Create balanced and realistic future km/yr, occupancy rate, and ride/carsharing share.

### ISSUE THREAD

**Issue by stefanpauliuk** [YaleCIE/RECC-ODYM#20]
We need to make sure that our vehicle use scenarios are consistent, and in particular, that passenger-km and future stock values are reasonable:
Using the tarket table, Create balanced and realistic future km/yr, occupancy rate, and ride/carsharing share.
Idea: make a small Excel helping tool to calculated stock from the other parameters.

**Comment by zerateltu** [comment]
'mass shared mobility' section (pp 91) of "ITF Transport Outlook 2019" report describes two scenarios for shared mobility but no detailed assumptions is disclosed. Maybe we can try to approach the organize to find out more details.

**Comment by Hertwich** [comment]
Good idea, @zerateltu, please do so!

**Comment by stefanpauliuk** [comment]
Currently used version of PKM, VKM, and OR data for all 19 model regions are in 
\Dropbox\G7 RECC\scenarios\Vehicle_Service_Calc_V3_vehicle_scenarios_compare_edit_sp.xlsx
