### ISSUE TITLE
Vehicle type split change/update

### ISSUE THREAD

**Issue by stefanpauliuk** [YaleCIE/RECC-ODYM#21]
We still have the electric vehicle share etc. from the 2010 ETP. need a good update!
See 3_SHA_TypeSplit_Vehicles_V2.3.xlsx

**Comment by zerateltu** [comment]
Figure 5.3 in "Energy Technology Perspectives 2017" report shows the global market penetration of different powertrains (2015-2060) under different scenarios.  Accordingly, pp 223-226 mention a couple of numbers (e.g., "_By 2020, 2.3% of all PLDVs on the road have ultra-low or zero-emission powertrains of three types: 0.9% PHEVs, 1.3% battery-electric vehicles (BEVs) and 0.05% fuel cell electric vehicles (FCEVs)._") that may be useful for intra-/extrapolate market evolution.
Ideally, we may obtain the complete dataset behind Fig.5.3 from IEA with the help from Eric.

**Comment by PaulWolfram** [comment]
Great idea, Qingshi! Would you be so kind to ask him?

**Comment by zerateltu** [comment]
> Great idea, Qingshi! Would you be so kind to ask him?

Sure, will do. Will cc you and Stefan on this.

**Comment by Hertwich** [comment]
The figures and underlying data can be found here https://www.iea.org/reports/energy-technology-perspectives-2017

**Comment by stefanpauliuk** [comment]
I back-calculated the inflow from the stock figures and converted to %, the result is now part of the RECC database. May swith from linear to spline interpolation as current result shows small discontinuities.
