### ISSUE TITLE
Steffi Feedback on RECC global

### ISSUE THREAD

**Issue by stefanpauliuk** [YaleCIE/RECC-ODYM#22]
Steffi:
Insgesamt habe ich 2 x 1_F, 1 x 2_S, 3 x 3_LT und 3 x 3_MC- Dateien übernommen sowie in den 4 von Dir gelb markierten Dateien Ergänzungen vorgenommen. Habe ich noch etwas übersehen?
-- ALL 1_F, 2_S, 3_MC, and 3_LT FILES for appliances, industry, and nonresbuildings_g:
    + Please check sheet order: First the Cover sheet, then the data sheet, then other ancillary sheets, and finally, the log and ref sheets
    + log and ref sheets lacking (cf. attached 3_MC_RECC_Vehicles_V1.1.xlsx as examples) (make sure that exact rows and columns are used for future machine-readability)
    + nonres_agg building labels were changed to:
        nonres_agg_hotels
        nonres_agg_governmental
        nonres_agg_office
        nonres_agg_retail
1_F_RECC_FinalProducts_appliances_V1.0
    + unit lacking (both on cover and on values master sheets)
    + Scenario LED and combination SSP1 and RCP2.6 are lacking! USING same values as for SSP1 and Baseline(unmitigated) for now!
1_F_RECC_FinalProducts_industry_V1.0
    + Scenario combination LED and Baseline(unmitigated) is lacking! USING same values as for RCP2.6 for now!
    + How are LED values determined?
2_S_RECC_FinalProducts_nonresbuildings_g_V1.0
    + for which scenario are the data reported?
4_EI_ManufacturingEnergyIntensity_V2.2
    + no data sources/references/explanations could be found for the added data.

**Comment by stefanpauliuk** [comment]
Thanks for the update Steffi! I checked all files and added the changes to the RECC project database mirror on
\Dropbox\G7 RECC\Data\RECC_Database\CURRENT_V2_4
Please use those files from now on, other changes will be overwritten!

OK:
1_F_RECC_FinalProducts_appliances_V1.0, added log and ref sheets.
1_F_RECC_FinalProducts_industry_V1.0, added log and ref sheets.
2_S_RECC_FinalProducts_nonresbuildings_g_V1.0, added log and ref sheets. Scenario values are all the same, so I kept the current indices Nc (and no R and S aspects).
Still need to answer: For which scenario are the data reported?
3_LT_RECC_ProductLifetime_appliances_V1.0, added log and ref sheets.
3_LT_RECC_ProductLifetime_industry_V1.0, added log and ref sheets.
3_LT_RECC_ProductLifetime_nonresbuildings_g_V1.0, added log and ref sheets.
3_MC_RECC_appliances_V1.1, OK, no changes.
3_MC_RECC_Nonresbuildings_g_V1.0, added log and ref sheets.
3_MC_RECC_industry_V1.1, OK from previous update, no changes.

**More work required:** 
(high priority)
2_S_RECC_FinalProducts_nonresbuildings_g_V1.0, still need to answer: For which scenario are the data reported?
4_EI_ManufacturingEnergyIntensity_V2.2, please send updated file with data sources, was not in list that you sent!

(medium priority)
+ Need LTE extension for ind/app/nrbg!
+ Need Eol-RR improvement assumptions for appliances
+ add plastics data to 3_MC_appliances!
+ add plastics to  4_PY_EoL_RR and 4_PY_Manufacturing

**Comment by stefanpauliuk** [comment]
Lifetime extension is now also programmed for ind, app, and nrbg, but still needs testing for correctness.

**Comment by stefanpauliuk** [comment]
The following items:
2_S_RECC_FinalProducts_nonresbuildings_g_V1.0, still need to answer: For which scenario are the data reported?
4_EI_ManufacturingEnergyIntensity_V2.2, please send updated file with data sources, was not in list that you sent!
were resolved bilaterally.

**Comment by SteffiKlose** [comment]
Lieber Stefan,

anbei die Datei. Da ich mich (zum jetzigen Stand) nicht mit der
Energieintensität beschäftigen werde, sind nicht alle Produkte enthalten.
Bei Bedarf hole ich das nach.

Viele Grüße
Steffi

**Comment by stefanpauliuk** [comment]
Hi @SteffiKlose this issue is closed now, we can take the next iteration on manufacturing energy intensity in a new issue when needed.
