### ISSUE TITLE
FileNotFoundError: \RECC_ParameterDict files

### ISSUE THREAD

**Issue by CBreton026** [YaleCIE/RECC-ODYM#34]
Hi, 

First of all, thank you for publishing and maintaining this repository. I recently installed a copy of ODYM-RECC to explore the model, run some scenarios for Canada, and see how I could use ODYM-RECC for my PhD. 

However, when I launch 'ODYM_RECC_Main.py' with the config file 'RECC_Config_V2_4.xlsx', I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '~\\ODYM\\RECC-Database\\ODYM_RECC_v2_4_Database\\RECC_ParameterDict_Global_North.dat'`

I looked in the ODYM_RECC_v2_4_Database (https://zenodo.org/record/4671644#.Yfl8EOrMIhQ) to try and change the path if necessary, but I couldn't find any RECC_ParameterDict_ files for the different regions. I also looked at previous versions of the database (v2_2, https://zenodo.org/record/3566865#.Yfl7uurMIhQ), but they do not seem to include the ParamaterDict files.

Could you help me figure out this issue? Are the ParameterDict files confidential?
Best regards,

**Comment by stefanpauliuk** [comment]
Hi Charles,
parsing all parameters takes a long time, which is why the RECC model dumps the parsed parameter data into a .dat file (pickle dump) and uses this .dat file if it can find one. 

If you have never run the model before, there is of course no dat file, and RECC will read the parameters instead.
This is done automatically with a try/except clause, which is why I am surprised that you get this error.
Exactly which line of code throws the error?

**Comment by CBreton026** [comment]
Hi Stefan,

I think I found the problem. In the 3_EI_Products_UsePhase_resbuildings.xlsx data file, in row 698, cols BM-BQ (65-69), there is a formula error (#REF!). These cells are fore R32CHN, 2015, MFH_Standard.

For R32CHN, 2014, MFH_Standard (Row 697, col 65) the formula is `=BM$696*E698/E$696`.
For R32CHN, 2015, MFH_Standard (Row 698, col 65) the formula is `=BM$696*#REF!/E$696 `

Correcting the #REF! error fixed the problem. Am I correct assuming that the #REF! value should be E698 as well? Are the SSP1 values for China scaled by the same factor as the USA SSP1 values?

**Comment by stefanpauliuk** [comment]
Hi Charles, yes this is the right fix indeed! 

It is unclear to me how and when the #REF error came into the database. Obviously, when we calculated our results, it was not there, else the import routine would have crashed, as you experienced.
